'use server';
/**
 * @fileOverview An AI mentor flow for generating high-performance marketing and business content.
 * Enhanced with cost tracking, caching, and improved prompts.
 */


import { ai, KIMI_MODELS } from '@/ai/genkit';
import { z } from 'genkit';
import { recordUsage } from '@/ai/analytics';
import { globalSemanticCache, isCacheableQuery } from '@/ai/core/semantic-cache';
import { estimateTokenCount } from '@/ai/core/tokenizer';
import { detectInjection } from '@/ai/guardrails';
import { logger } from '@/lib/logger';

const ContentGenInputSchema = z.object({
  contentType: z.enum(['ad_copy', 'email_funnel', 'landing_page_headline', 'value_proposition', 'social_post', 'blog_outline']).describe('The type of content to generate.'),
  businessContext: z.string().describe('The context or description of the business.'),
  targetAudience: z.string().describe('The primary target audience.'),
  tone: z.enum(['professional', 'casual', 'urgent', 'inspirational']).optional().describe('Tone of the content.'),
  userId: z.string().optional().describe('User ID for caching and tracking.'),
});
export type ContentGenInput = z.infer<typeof ContentGenInputSchema>;

const ContentGenOutputSchema = z.object({
  generatedContent: z.string().describe('The high-performance content generated by the AI.'),
  strategicTips: z.array(z.string()).describe('Strategic tips to maximize the effectiveness of this content.'),
  variations: z.array(z.string()).optional().describe('Alternative versions of the content.'),
});
export type ContentGenOutput = z.infer<typeof ContentGenOutputSchema>;

export async function generateMentorContent(input: ContentGenInput): Promise<ContentGenOutput> {
  const startTime = Date.now();
  
  try {
    // Security check
    const injectionCheck = detectInjection(input.businessContext + ' ' + input.targetAudience);
    if (!injectionCheck.passed && injectionCheck.confidence > 0.8) {
      throw new Error('Invalid input detected');
    }

    // Check cache for similar requests
    const cacheKey = `${input.contentType}:${input.businessContext}:${input.targetAudience}:${input.tone || 'default'}`;
    if (input.userId && isCacheableQuery(cacheKey)) {
      const cached = await globalSemanticCache.get(cacheKey, input.userId);
      if (cached) {
        logger.info('[ContentGen] Cache hit', { userId: input.userId, contentType: input.contentType });
        return JSON.parse(cached.response);
      }
    }

    const result = await aiMentorContentGenFlow(input);
    
    // Record usage
    const durationMs = Date.now() - startTime;
    const outputTokens = estimateTokenCount(JSON.stringify(result));
    
    recordUsage({
      timestamp: startTime,
      userId: input.userId || 'anonymous',
      model: KIMI_MODELS.STANDARD,
      inputTokens: estimateTokenCount(input.businessContext + input.targetAudience),
      outputTokens,
      operation: 'content_gen',
      cached: false,
      durationMs,
    });

    // Cache result
    if (input.userId && isCacheableQuery(cacheKey)) {
      globalSemanticCache.set(cacheKey, JSON.stringify(result), {
        model: KIMI_MODELS.STANDARD,
        tokensUsed: outputTokens,
        timestamp: Date.now(),
        userId: input.userId,
      });
    }

    return result;
  } catch (error) {
    logger.error('[ContentGen] Error generating content', error instanceof Error ? error : new Error(String(error)));
    throw error;
  }
}

const contentPrompt = ai.definePrompt({
  name: 'aiMentorContentGenPrompt',
  model: 'kimi',
  config: {
    model: KIMI_MODELS.STANDARD,
  },
  input: { schema: ContentGenInputSchema },
  output: { schema: ContentGenOutputSchema },
  prompt: `You are an elite AI Digital Marketing Coach and Copywriter for Soma Digital. You specialize in teaching members how to create high-converting content, manage social media, and optimize for SEO.

Generate high-converting {{{contentType}}} for the following business:

Business Context: {{{businessContext}}}
Target Audience: {{{targetAudience}}}
Tone: {{{tone}}}

Requirements:
1. Hook the reader in the first 10 words
2. Focus on benefits, not features
3. Include a clear call-to-action
4. Use persuasive language patterns
5. Keep it scannable and readable

Provide the content along with 3-5 strategic tips for maximizing its effectiveness. Optionally provide 2 alternative variations.`,
});

const aiMentorContentGenFlow = ai.defineFlow(
  {
    name: 'aiMentorContentGenFlow',
    inputSchema: ContentGenInputSchema,
    outputSchema: ContentGenOutputSchema,
  },
  async (input) => {
    const { output } = await contentPrompt(input);
    return output!;
  }
);
