'use server';
/**
 * @fileOverview An AI mentor flow for generating high-performance marketing and business content.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const ContentGenInputSchema = z.object({
  contentType: z.enum(['ad_copy', 'email_funnel', 'landing_page_headline', 'value_proposition']).describe('The type of content to generate.'),
  businessContext: z.string().describe('The context or description of the business.'),
  targetAudience: z.string().describe('The primary target audience.'),
});
export type ContentGenInput = z.infer<typeof ContentGenInputSchema>;

const ContentGenOutputSchema = z.object({
  generatedContent: z.string().describe('The high-performance content generated by the AI.'),
  strategicTips: z.array(z.string()).describe('Strategic tips to maximize the effectiveness of this content.'),
});
export type ContentGenOutput = z.infer<typeof ContentGenOutputSchema>;

export async function generateMentorContent(input: ContentGenInput): Promise<ContentGenOutput> {
  return aiMentorContentGenFlow(input);
}

const contentPrompt = ai.definePrompt({
  name: 'aiMentorContentGenPrompt',
  input: { schema: ContentGenInputSchema },
  output: { schema: ContentGenOutputSchema },
  prompt: `You are an elite AI Digital Marketing Coach and Copywriter for Soma Digital. You specialize in teaching members how to create high-converting content, manage social media, and optimize for SEO.
  Generate high-converting {{{contentType}}} for the following business:
  
  Business Context: {{{businessContext}}}
  Target Audience: {{{targetAudience}}}

  Ensure the tone is professional, futuristic, and highly persuasive. Focus on digital economy trends.`,
});

const aiMentorContentGenFlow = ai.defineFlow(
  {
    name: 'aiMentorContentGenFlow',
    inputSchema: ContentGenInputSchema,
    outputSchema: ContentGenOutputSchema,
  },
  async (input) => {
    const { output } = await contentPrompt(input);
    return output!;
  }
);